export const userData = {
   'jull-altamirano': {
      nombres: 'Jull',
      apellidos: 'Altamirano',
      puesto: 'Desarrollador de Sistemas',
      empresa: 'Peru Masivo',
      codigo_telefono: '+51',
      telefono: 931748317,
      telefono_empresa: '01-2003000',
      whatsapp: 'https://wa.link/uh623u',
      anexo: '-',
      email: 'jullpa@perumasivo.net',
      direccion: 'Av. Antonio Miroquezada #457 Int 1201',
      distrito: 'Magdalena',
      ciudad: 'Lima',
      pais: 'Peru',
      img_link: '',
   },
   'oscar-vanegas': {
      nombres: 'Oscar',
      apellidos: 'Vanegas',
      puesto: 'Gerente General',
      empresa: 'Peru Masivo',
      codigo_telefono: '+51',
      telefono: 983321933,
      telefono_empresa: '01-2003000',
      whatsapp: 'https://wa.link/uh623u',
      anexo: '1201',
      email: 'oscarvg@perumasivo.com',
      direccion: 'Av. Antonio Miroquezada #457 Int 1201',
      distrito: 'Magdalena',
      ciudad: 'Lima',
      pais: 'Peru',
      img_link: '/oscar-vanegas.webp',
   },
};
   